### PR TITLE
✨ Include sample survey metadata and utils

### PR DESCRIPTION
**Pull request by shunkosa**
## Summary
* Add sample survey metadata (v0.1) with the separate package directory
  * https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_mpd.htm
* Add unit test for validation rule (not in the base package)
* Add sample contact and relationship records

You can easily verify them by the following commands after you create a scratch org:
1. `sfdx force:source:push`
2. `sfdx force:user:permset:assign -n GRMS_App_Admin`
3. `sfdx sfdx force:data:tree:import -p data/plan.json`
4. `sfdx force:apex:test:run --testlevel RunLocalTests --synchronous`

### CODE REVIEW

**Comment by eehjunggnujhee** [comment]
@shunkosa We are close!
We have a global picklist value error. [I don't see "Flower__c" from the original Metecho branch. ](https://github.com/SFDO-Community-Sprints/GrassrootsSurveySalesforcePackage/blob/metecho/sample-surveys/force-app/main/default/objects/GRMS_Survey__c/GRMS_Survey__c.object-meta.xml)
`TYPE   PROJECT PATH                                                                                             PROBLEM
─────  
Error  grms-sample-surveys/main/default/objects/GRMS_Survey__c/recordTypes/Homecare.recordType-meta.xml         Global value set 'Flower__c' in record type 'Homecare' on the entity 'GRMS_Survey__c' cannot be resolved (1128:25)
Error  grms-sample-surveys/main/default/objects/GRMS_Survey__c/recordTypes/Disaster_Relief.recordType-meta.xml  Global value set 'Flower__c' in record type 'Disaster Relief' on the entity 'GRMS_Survey__c' cannot be resolved (860:25)
ERROR running force:source:push:  Push failed. 

Try this: 
Check the order of your dependencies and ensure all metadata is included.`

**Comment by shunkosa** [comment]
Oh, I forgot to delete my sample field. But not sure why I succeeded pushing the current metadata to a new scratch org..

**Comment by shunkosa** [comment]
Ah, fixed the directory name...🤦🏻

**Comment by eehjunggnujhee** [comment]
> Oh, I forgot to delete my sample field. But not sure why I succeeded pushing the current metadata to a new scratch org..

I thought that too. It was strange...

**Comment by eehjunggnujhee** [comment]
@shunkosa  Strange!
`Error  force-app/main/default/objects/Contact.object-meta.xml  This custom field is referenced elsewhere in salesforce.com. : Apex Class - GRMS_ContactValidationRuleTest.
ERROR running force:source:push:  Push failed.`

**Comment by eehjunggnujhee** [comment]
@shunkosa  All works well. Merging
`== Test Results
TEST NAME                                                        OUTCOME  MESSAGE  RUNTIME (MS)
───────────────────────────────────────────────────────────────  ───────  ───────  ────────────
GRMS_ContactValidationRuleTest.testSurveyClientFieldRestriction  Pass              228         
GRMS_ContactValidationRuleTest.testSurveyUserFieldRestriction    Pass              64          
GRMS_ContactValidationRuleTest.testUserClientRelation            Pass              179         
`

**Review by eehjunggnujhee — APPROVED** [review]

**Pull request merged**
